name: Deploy

on:
  push:
    branches: [week4]


jobs:
  checks:
    uses: ./.github/workflows/type-check.yaml

  build:
    needs: checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [back]
        include:
          - service: front
            vite-api-url: https://v1smolensky.xyz/api
      fail-fast: false
    env:
      IMAGE_SHA_NAME: '${{ vars.DOCKER_USERNAME }}/todo-${{ matrix.service }}:${{ github.sha }}'
      IMAGE_LATEST_NAME: '${{ vars.DOCKER_USERNAME }}/todo-${{ matrix.service }}:latest'
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images
        run: |
          if [[ ${{ matrix.service }} == "front" ]]; then
            docker build --build-arg VITE_API_URL=${{ matrix.vite-api-url }} -t $IMAGE_SHA_NAME -t $IMAGE_LATEST_NAME .
          else
            docker build -t $IMAGE_SHA_NAME -t $IMAGE_LATEST_NAME .
          fi
          

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push to Docker Hub
        run: |
          docker push $IMAGE_SHA_NAME |
          docker push $IMAGE_LATEST_NAME

#  deploy:
#
#  verify:
#
#  notify: